name: x86-64 Pull and Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_images:
        required: true

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "linux/amd64"
          docker save "${image}" -o "${image//\//_}.tar"
        done

    - name: Create tar.gz files
      run: tar -czvf docker_images.tar.gz *.tar
  

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker_images.tar.gz
        path: docker_images.tar.gz
        retention-days: 1  

    - name: Clean up intermediate files
      run: |
        rm docker_images.tar.gz
