name: Download_docker_images

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: 
          '多个镜像名称请用英文逗号分开
           多个镜像下载后会将每个镜像单独保存成一个tar
           再将多个tar合并保存成一个tar包'
        required: true

jobs:
  Download_docker_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "linux/amd64"
          docker save "${image}" -o "${image//\//_}.tar"
        done

    - name: Merge tar packages
      run: tar -czvf docker_images.tar.gz *.tar
  

    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: docker_images
        path: docker_images.tar.gz
        retention-days: 1  

    - name: Clean files
      run: |
        rm docker_images.tar.gz
